export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  SET_USER: "SET_USER",
  // EMPTY_BASKET: "EMPTY_BASKET",
  // SET_ORDERS: "SET_ORDERS",
  // SET_PRODUCTS: "SET_PRODUCTS",
  // SET_PRODUCT: "SET_PRODUCT",
  // SET_SEARCH: "SET_SEARCH",
  // SET_LOADING: "SET_LOADING",
  // SET_ERROR: "SET_ERROR",
  // SET_MESSAGE: "SET_MESSAGE",
};
